version: "3.4"

services:
  site:
    build:
      context: ./site
      dockerfile: Dockerfile
    networks:
      epigma_local:
    depends_on:
      - api
    ports:
      - 80:5000
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - db_uri=mongodb://epigma.mongo.docker/storage_epigma
      - PORT=3000
    networks:
      epigma_local:
        aliases:
          - epigma.api.docker
    volumes:
      - assets_data:/var/epigma/assets
    depends_on:
      - mongo
    ports:
      - 3000:3000
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      epigma_local:
        aliases:
          - epigma.mongo.docker


networks:
  epigma_local:

volumes:
  mongo_data:
  assets_data: